/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package monolitosemaforo.logic;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author mac
 */
public class Light extends javax.swing.JPanel {

    /**
     * Creates new form Light
     */
    private boolean red;
    private boolean yellow;
    private boolean green;
    private boolean off;

    public Light() {
        red=false;
        yellow=false;
        green=false;
        off=true;
    }

    public void red() {
        red=true;
        yellow=false;
        green=false;
        repaint();
    }

    public void yellow() {
        red=false;
        yellow=true;
        green=false;
        repaint();
    }

    public void green() {
        red=false;
        yellow=false;
        green=true;
        repaint();
    }
    
     public void off() {
        red=false;
        yellow=false;
        green=false;
        off=true;
        repaint();
    }

    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(red) {
            g.setColor(Color.red);
            g.fillOval(20,20,30,30);
            g.setColor(Color.black);
            g.drawOval(20,55,30,30);
            g.drawOval(20,90,30,30);
            g.drawRect(5,5,60,130);
            g.setColor(Color.ORANGE);
            g.fillRect(20,136,30,80);
        }
        
        else if(yellow) {
            g.setColor(Color.yellow);
            g.fillOval(20,55,30,30);
            g.setColor(Color.black);
            g.drawRect(5,5,60,130);
            g.drawOval(20,20,30,30);
            g.drawOval(20,90,30,30);
            g.setColor(Color.ORANGE);
            g.fillRect(20,136,30,80);
        }
        
        else if(green) {
            g.setColor(Color.green);
            g.fillOval(20,90,30,30);
            g.setColor(Color.black);
            g.drawRect(5,5,60,130);
            g.drawOval(20,20,30,30);
            g.drawOval(20,55,30,30);
            g.setColor(Color.ORANGE);
            g.fillRect(20,136,30,80);
        }
        
        else if(off){
            g.setColor(Color.black);
            g.drawRect(5,5,60,130);
            g.drawOval(20,20,30,30);
            g.drawOval(20,55,30,30);
            g.drawOval(20,90,30,30);
            g.setColor(Color.ORANGE);
            g.fillRect(20,136,30,80);
        }
    }
    
    public Dimension getPreferredSize() {
        return new Dimension(70,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
