/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.Timer;
import java.util.TimerTask;

import persistence.Light;

/**
 *
 * @author jeison.alarcon
 */
public class SemaphoresView extends javax.swing.JFrame {
    
    private Light semaphore1 = new Light();
    private Light semaphore2 = new Light();
    private Light semaphore3 = new Light();
    private Light semaphore4 = new Light();

    Timer timer = new Timer();

    /**
     * Creates new form vista1
     */
    public SemaphoresView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Semaforo");
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setSize(200, 200);
        jPanel1.setLayout(new FlowLayout(FlowLayout.CENTER));
        semaphore1.setSize(100, 90);
        jPanel1.add(semaphore1);
        getContentPane().add(jPanel1, BorderLayout.CENTER);
        jPanel2.setSize(200, 200);
        jPanel2.setLayout(new FlowLayout(FlowLayout.CENTER));
        semaphore2.setSize(100, 90);
        jPanel2.add(semaphore2);
        getContentPane().add(jPanel2, BorderLayout.CENTER);
        jPanel3.setSize(200, 200);
        jPanel3.setLayout(new FlowLayout(FlowLayout.CENTER));
        semaphore3.setSize(100, 90);
        jPanel3.add(semaphore3);
        getContentPane().add(jPanel3, BorderLayout.CENTER);
        jPanel4.setSize(200, 200);
        jPanel4.setLayout(new FlowLayout(FlowLayout.CENTER));
        semaphore4.setSize(100, 90);
        jPanel4.add(semaphore4);
        getContentPane().add(jPanel4, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemaphoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemaphoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemaphoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemaphoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SemaphoresView().setVisible(true);
        });
    }
    
    public void red1(){
        System.out.println("00001011 - Luz Roja Semaforo 1 Grupo 1");
        semaphore1.red();
        System.out.println("00001011 - Luz Roja Semaforo 2 Grupo 1");
        semaphore2.red();
    }

    public void yellow1(){
        System.out.println("00000011 - Luz Amarilla Semaforo 1 Grupo 1");
        semaphore1.yellow();
        System.out.println("00000011 - Luz Amarilla Semaforo 2 Grupo 1");
        semaphore2.yellow();
    }

    public void green1(){
        System.out.println("00100011 - Luz Verde Semaforo 1 Grupo 1");
        semaphore1.green();
        System.out.println("00100011 - Luz Verde Semaforo 2 Grupo 1");
        semaphore2.green();
    }

    public void red2(){
        System.out.println("00001011 - Luz Roja Semaforo 1 Grupo 2");
        semaphore3.red();
        System.out.println("00001011 - Luz Roja Semaforo 2 Grupo 2");
        semaphore4.red();
    }

    public void yellow2(){
        System.out.println("00000011 - Luz Amarilla Semaforo 1 Grupo 2");
        semaphore3.yellow();
        System.out.println("00000011 - Luz Amarilla Semaforo 2 Grupo 2");
        semaphore4.yellow();
    }

    public void green2(){
        System.out.println("00100011 - Luz Verde Semaforo 1 Grupo 2");
        semaphore3.green();
        System.out.println("00100011 - Luz Verde Semaforo 2 Grupo 2");
        semaphore4.green();
    }

    public void off(){
        System.out.println("00000000 - Semaforos Apagados");
        semaphore1.off();
        semaphore2.off();
        semaphore3.off();
        semaphore4.off();
        timer.cancel();
    }


    public void auto() {
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                semaphore1.red();
                semaphore2.red();
                System.out.println("00001011 - Luz Roja Automatico");
            }
        }, 4000, 4000);

        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                semaphore1.yellow();
                semaphore2.yellow();
                System.out.println("00000011 - Luz Amarilla Automatico");
            }
        }, 4000, 4000);

        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                semaphore1.green();
                semaphore2.green();
                System.out.println("00100011 - Luz Verde Automatico");
            }
        }, 4000, 4000);

        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                semaphore1.yellow();
                semaphore2.yellow();
                System.out.println("00000011 - Luz Amarilla Automatico");
            }
        }, 4000, 4000);

    }

    public void fail(){
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                semaphore1.fail();
                System.out.println("00001011 - Intermitencia: Falla ");
            }
        }, 0, 1000);

        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                semaphore1.off();
                System.out.println("00001011 - Intermitencia: Falla ");
            }
        }, 100, 1000);


    }
    public void repair(){
        System.out.println("Semaforo Reparado reiniciando el sistema el sistema");
        semaphore1.off();
        timer.cancel();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
